// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: agent.proto

package noxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_RouteDecision_FullMethodName      = "/noxy.agent.AgentService/RouteDecision"
	AgentService_GetDecisionOutcome_FullMethodName = "/noxy.agent.AgentService/GetDecisionOutcome"
	AgentService_GetQuota_FullMethodName           = "/noxy.agent.AgentService/GetQuota"
	AgentService_GetIdentityDevices_FullMethodName = "/noxy.agent.AgentService/GetIdentityDevices"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI agent → relay: route encrypted human-in-the-loop decisions to wallet devices.
type AgentServiceClient interface {
	RouteDecision(ctx context.Context, in *RouteDecisionRequest, opts ...grpc.CallOption) (*DeliveryOutcome, error)
	GetDecisionOutcome(ctx context.Context, in *GetDecisionOutcomeRequest, opts ...grpc.CallOption) (*GetDecisionOutcomeResponse, error)
	GetQuota(ctx context.Context, in *GetQuotaRequest, opts ...grpc.CallOption) (*GetQuotaResponse, error)
	GetIdentityDevices(ctx context.Context, in *GetIdentityDevicesRequest, opts ...grpc.CallOption) (*GetIdentityDevicesResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RouteDecision(ctx context.Context, in *RouteDecisionRequest, opts ...grpc.CallOption) (*DeliveryOutcome, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryOutcome)
	err := c.cc.Invoke(ctx, AgentService_RouteDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetDecisionOutcome(ctx context.Context, in *GetDecisionOutcomeRequest, opts ...grpc.CallOption) (*GetDecisionOutcomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDecisionOutcomeResponse)
	err := c.cc.Invoke(ctx, AgentService_GetDecisionOutcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetQuota(ctx context.Context, in *GetQuotaRequest, opts ...grpc.CallOption) (*GetQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuotaResponse)
	err := c.cc.Invoke(ctx, AgentService_GetQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetIdentityDevices(ctx context.Context, in *GetIdentityDevicesRequest, opts ...grpc.CallOption) (*GetIdentityDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdentityDevicesResponse)
	err := c.cc.Invoke(ctx, AgentService_GetIdentityDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AI agent → relay: route encrypted human-in-the-loop decisions to wallet devices.
type AgentServiceServer interface {
	RouteDecision(context.Context, *RouteDecisionRequest) (*DeliveryOutcome, error)
	GetDecisionOutcome(context.Context, *GetDecisionOutcomeRequest) (*GetDecisionOutcomeResponse, error)
	GetQuota(context.Context, *GetQuotaRequest) (*GetQuotaResponse, error)
	GetIdentityDevices(context.Context, *GetIdentityDevicesRequest) (*GetIdentityDevicesResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) RouteDecision(context.Context, *RouteDecisionRequest) (*DeliveryOutcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RouteDecision not implemented")
}
func (UnimplementedAgentServiceServer) GetDecisionOutcome(context.Context, *GetDecisionOutcomeRequest) (*GetDecisionOutcomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDecisionOutcome not implemented")
}
func (UnimplementedAgentServiceServer) GetQuota(context.Context, *GetQuotaRequest) (*GetQuotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuota not implemented")
}
func (UnimplementedAgentServiceServer) GetIdentityDevices(context.Context, *GetIdentityDevicesRequest) (*GetIdentityDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentityDevices not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_RouteDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RouteDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RouteDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RouteDecision(ctx, req.(*RouteDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetDecisionOutcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDecisionOutcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetDecisionOutcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetDecisionOutcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetDecisionOutcome(ctx, req.(*GetDecisionOutcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetQuota(ctx, req.(*GetQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetIdentityDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetIdentityDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetIdentityDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetIdentityDevices(ctx, req.(*GetIdentityDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "noxy.agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RouteDecision",
			Handler:    _AgentService_RouteDecision_Handler,
		},
		{
			MethodName: "GetDecisionOutcome",
			Handler:    _AgentService_GetDecisionOutcome_Handler,
		},
		{
			MethodName: "GetQuota",
			Handler:    _AgentService_GetQuota_Handler,
		},
		{
			MethodName: "GetIdentityDevices",
			Handler:    _AgentService_GetIdentityDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
