// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: noxy.proto

package noxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERED  DeliveryStatus = 0
	DeliveryStatus_QUEUED     DeliveryStatus = 1
	DeliveryStatus_NO_DEVICES DeliveryStatus = 2
	DeliveryStatus_REJECTED   DeliveryStatus = 3
	DeliveryStatus_ERROR      DeliveryStatus = 4
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERED",
		1: "QUEUED",
		2: "NO_DEVICES",
		3: "REJECTED",
		4: "ERROR",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERED":  0,
		"QUEUED":     1,
		"NO_DEVICES": 2,
		"REJECTED":   3,
		"ERROR":      4,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_noxy_proto_enumTypes[0].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_noxy_proto_enumTypes[0]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_noxy_proto_rawDescGZIP(), []int{0}
}

type QuotaStatus int32

const (
	QuotaStatus_QUOTA_ACTIVE    QuotaStatus = 0
	QuotaStatus_QUOTA_SUSPENDED QuotaStatus = 1
	QuotaStatus_QUOTA_DELETED   QuotaStatus = 2
)

// Enum value maps for QuotaStatus.
var (
	QuotaStatus_name = map[int32]string{
		0: "QUOTA_ACTIVE",
		1: "QUOTA_SUSPENDED",
		2: "QUOTA_DELETED",
	}
	QuotaStatus_value = map[string]int32{
		"QUOTA_ACTIVE":    0,
		"QUOTA_SUSPENDED": 1,
		"QUOTA_DELETED":   2,
	}
)

func (x QuotaStatus) Enum() *QuotaStatus {
	p := new(QuotaStatus)
	*p = x
	return p
}

func (x QuotaStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuotaStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_noxy_proto_enumTypes[1].Descriptor()
}

func (QuotaStatus) Type() protoreflect.EnumType {
	return &file_noxy_proto_enumTypes[1]
}

func (x QuotaStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuotaStatus.Descriptor instead.
func (QuotaStatus) EnumDescriptor() ([]byte, []int) {
	return file_noxy_proto_rawDescGZIP(), []int{1}
}

type PushNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ciphertext     []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	TtlSeconds     uint32                 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	TargetDeviceId string                 `protobuf:"bytes,4,opt,name=target_device_id,json=targetDeviceId,proto3" json:"target_device_id,omitempty"`
	KyberCt        []byte                 `protobuf:"bytes,5,opt,name=kyber_ct,json=kyberCt,proto3" json:"kyber_ct,omitempty"`
	Nonce          []byte                 `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushNotificationRequest) Reset() {
	*x = PushNotificationRequest{}
	mi := &file_noxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotificationRequest) ProtoMessage() {}

func (x *PushNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotificationRequest.ProtoReflect.Descriptor instead.
func (*PushNotificationRequest) Descriptor() ([]byte, []int) {
	return file_noxy_proto_rawDescGZIP(), []int{0}
}

func (x *PushNotificationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PushNotificationRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *PushNotificationRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *PushNotificationRequest) GetTargetDeviceId() string {
	if x != nil {
		return x.TargetDeviceId
	}
	return ""
}

func (x *PushNotificationRequest) GetKyberCt() []byte {
	if x != nil {
		return x.KyberCt
	}
	return nil
}

func (x *PushNotificationRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        DeliveryStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=noxy.push.DeliveryStatus" json:"status,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_noxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_noxy_proto_rawDescGZIP(), []int{1}
}

func (x *PushResponse) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERED
}

func (x *PushResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuotaRequest) Reset() {
	*x = GetQuotaRequest{}
	mi := &file_noxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaRequest) ProtoMessage() {}

func (x *GetQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaRequest.ProtoReflect.Descriptor instead.
func (*GetQuotaRequest) Descriptor() ([]byte, []int) {
	return file_noxy_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuotaRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetQuotaResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AppName        string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	QuotaTotal     uint64                 `protobuf:"varint,3,opt,name=quota_total,json=quotaTotal,proto3" json:"quota_total,omitempty"`
	QuotaRemaining uint64                 `protobuf:"varint,4,opt,name=quota_remaining,json=quotaRemaining,proto3" json:"quota_remaining,omitempty"`
	Status         QuotaStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=noxy.push.QuotaStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetQuotaResponse) Reset() {
	*x = GetQuotaResponse{}
	mi := &file_noxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaResponse) ProtoMessage() {}

func (x *GetQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaResponse.ProtoReflect.Descriptor instead.
func (*GetQuotaResponse) Descriptor() ([]byte, []int) {
	return file_noxy_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuotaResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetQuotaResponse) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *GetQuotaResponse) GetQuotaTotal() uint64 {
	if x != nil {
		return x.QuotaTotal
	}
	return 0
}

func (x *GetQuotaResponse) GetQuotaRemaining() uint64 {
	if x != nil {
		return x.QuotaRemaining
	}
	return 0
}

func (x *GetQuotaResponse) GetStatus() QuotaStatus {
	if x != nil {
		return x.Status
	}
	return QuotaStatus_QUOTA_ACTIVE
}

type GetIdentityDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	IdentityId    string                 `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"` // wallet address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityDevicesRequest) Reset() {
	*x = GetIdentityDevicesRequest{}
	mi := &file_noxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityDevicesRequest) ProtoMessage() {}

func (x *GetIdentityDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityDevicesRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityDevicesRequest) Descriptor() ([]byte, []int) {
	return file_noxy_proto_rawDescGZIP(), []int{4}
}

func (x *GetIdentityDevicesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetIdentityDevicesRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

type IdentityDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PqPublicKey   []byte                 `protobuf:"bytes,3,opt,name=pq_public_key,json=pqPublicKey,proto3" json:"pq_public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityDevice) Reset() {
	*x = IdentityDevice{}
	mi := &file_noxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityDevice) ProtoMessage() {}

func (x *IdentityDevice) ProtoReflect() protoreflect.Message {
	mi := &file_noxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityDevice.ProtoReflect.Descriptor instead.
func (*IdentityDevice) Descriptor() ([]byte, []int) {
	return file_noxy_proto_rawDescGZIP(), []int{5}
}

func (x *IdentityDevice) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *IdentityDevice) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *IdentityDevice) GetPqPublicKey() []byte {
	if x != nil {
		return x.PqPublicKey
	}
	return nil
}

type GetIdentityDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Devices       []*IdentityDevice      `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityDevicesResponse) Reset() {
	*x = GetIdentityDevicesResponse{}
	mi := &file_noxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityDevicesResponse) ProtoMessage() {}

func (x *GetIdentityDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetIdentityDevicesResponse) Descriptor() ([]byte, []int) {
	return file_noxy_proto_rawDescGZIP(), []int{6}
}

func (x *GetIdentityDevicesResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetIdentityDevicesResponse) GetDevices() []*IdentityDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

var File_noxy_proto protoreflect.FileDescriptor

const file_noxy_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"noxy.proto\x12\tnoxy.push\"\xd4\x01\n" +
	"\x17PushNotificationRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\rR\n" +
	"ttlSeconds\x12(\n" +
	"\x10target_device_id\x18\x04 \x01(\tR\x0etargetDeviceId\x12\x19\n" +
	"\bkyber_ct\x18\x05 \x01(\fR\akyberCt\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\fR\x05nonce\"`\n" +
	"\fPushResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.noxy.push.DeliveryStatusR\x06status\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"0\n" +
	"\x0fGetQuotaRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xc6\x01\n" +
	"\x10GetQuotaResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x1f\n" +
	"\vquota_total\x18\x03 \x01(\x04R\n" +
	"quotaTotal\x12'\n" +
	"\x0fquota_remaining\x18\x04 \x01(\x04R\x0equotaRemaining\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.noxy.push.QuotaStatusR\x06status\"[\n" +
	"\x19GetIdentityDevicesRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\"p\n" +
	"\x0eIdentityDevice\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\"\n" +
	"\rpq_public_key\x18\x03 \x01(\fR\vpqPublicKey\"p\n" +
	"\x1aGetIdentityDevicesResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x123\n" +
	"\adevices\x18\x02 \x03(\v2\x19.noxy.push.IdentityDeviceR\adevices*T\n" +
	"\x0eDeliveryStatus\x12\r\n" +
	"\tDELIVERED\x10\x00\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x01\x12\x0e\n" +
	"\n" +
	"NO_DEVICES\x10\x02\x12\f\n" +
	"\bREJECTED\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04*G\n" +
	"\vQuotaStatus\x12\x10\n" +
	"\fQUOTA_ACTIVE\x10\x00\x12\x13\n" +
	"\x0fQUOTA_SUSPENDED\x10\x01\x12\x11\n" +
	"\rQUOTA_DELETED\x10\x022\x86\x02\n" +
	"\vPushService\x12O\n" +
	"\x10PushNotification\x12\".noxy.push.PushNotificationRequest\x1a\x17.noxy.push.PushResponse\x12C\n" +
	"\bGetQuota\x12\x1a.noxy.push.GetQuotaRequest\x1a\x1b.noxy.push.GetQuotaResponse\x12a\n" +
	"\x12GetIdentityDevices\x12$.noxy.push.GetIdentityDevicesRequest\x1a%.noxy.push.GetIdentityDevicesResponseB*Z(github.com/noxy-network/go-sdk/grpc/noxyb\x06proto3"

var (
	file_noxy_proto_rawDescOnce sync.Once
	file_noxy_proto_rawDescData []byte
)

func file_noxy_proto_rawDescGZIP() []byte {
	file_noxy_proto_rawDescOnce.Do(func() {
		file_noxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_noxy_proto_rawDesc), len(file_noxy_proto_rawDesc)))
	})
	return file_noxy_proto_rawDescData
}

var file_noxy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_noxy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_noxy_proto_goTypes = []any{
	(DeliveryStatus)(0),                // 0: noxy.push.DeliveryStatus
	(QuotaStatus)(0),                   // 1: noxy.push.QuotaStatus
	(*PushNotificationRequest)(nil),    // 2: noxy.push.PushNotificationRequest
	(*PushResponse)(nil),               // 3: noxy.push.PushResponse
	(*GetQuotaRequest)(nil),            // 4: noxy.push.GetQuotaRequest
	(*GetQuotaResponse)(nil),           // 5: noxy.push.GetQuotaResponse
	(*GetIdentityDevicesRequest)(nil),  // 6: noxy.push.GetIdentityDevicesRequest
	(*IdentityDevice)(nil),             // 7: noxy.push.IdentityDevice
	(*GetIdentityDevicesResponse)(nil), // 8: noxy.push.GetIdentityDevicesResponse
}
var file_noxy_proto_depIdxs = []int32{
	0, // 0: noxy.push.PushResponse.status:type_name -> noxy.push.DeliveryStatus
	1, // 1: noxy.push.GetQuotaResponse.status:type_name -> noxy.push.QuotaStatus
	7, // 2: noxy.push.GetIdentityDevicesResponse.devices:type_name -> noxy.push.IdentityDevice
	2, // 3: noxy.push.PushService.PushNotification:input_type -> noxy.push.PushNotificationRequest
	4, // 4: noxy.push.PushService.GetQuota:input_type -> noxy.push.GetQuotaRequest
	6, // 5: noxy.push.PushService.GetIdentityDevices:input_type -> noxy.push.GetIdentityDevicesRequest
	3, // 6: noxy.push.PushService.PushNotification:output_type -> noxy.push.PushResponse
	5, // 7: noxy.push.PushService.GetQuota:output_type -> noxy.push.GetQuotaResponse
	8, // 8: noxy.push.PushService.GetIdentityDevices:output_type -> noxy.push.GetIdentityDevicesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_noxy_proto_init() }
func file_noxy_proto_init() {
	if File_noxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_noxy_proto_rawDesc), len(file_noxy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noxy_proto_goTypes,
		DependencyIndexes: file_noxy_proto_depIdxs,
		EnumInfos:         file_noxy_proto_enumTypes,
		MessageInfos:      file_noxy_proto_msgTypes,
	}.Build()
	File_noxy_proto = out.File
	file_noxy_proto_goTypes = nil
	file_noxy_proto_depIdxs = nil
}
